# CV content, English and Greek.
# Private details (address, phones, date of birth, marital status, TEE number,
# plain-text email) are deliberately left out: this is the public web edition.

CV = {
"en": {
  "lang": "en",
  "title": "Nikos Kalogerinis · CV",
  "name": "Nikos Kalogerinis",
  "role": "Electronic & Computer Engineer",
  "place": "Athens, Greece",
  "links": ["www.kalogerinis.net", "github.com/menthol1979"],
  "footer": "Nikos Kalogerinis · Curriculum Vitae",
  "page": "Page",
  "of": "of",
  "extra_title": "Languages & more",
  "extra": [
    ("English", "Cambridge Certificate of Proficiency"),
    ("French", "DELF A1, A3, A4"),
    ("Technical Chamber of Greece", "Member as Electronic Engineer, 2003 – 2013"),
    ("Military service", "Completed, 2006 – 2007"),
  ],
  "sections": [
    ("Education", [
      ("2002 – 2006", "Technical University of Crete, Chania", "MSc, School of Production Engineering & Management",
       "Specialization: Business Organization & Management.",
       ["Thesis: <em>Development of a web-based multi-criteria group decision support system</em>.",
        "Course average: 8.14 / 10."]),
      ("2002 – 2005", "Technical University of Crete, Chania", "MSc, School of Electronic & Computer Engineering",
       "Specialization: Communication Networks.",
       ["Thesis: <em>Energy-Aware Scoping Algorithm and Energy Saving Techniques for Wireless Sensor Networks</em>.",
        "Course average: 9.63 / 10."]),
      ("1996 – 2002", "Technical University of Crete, Chania", "Diploma in Electronic & Computer Engineering (5-year degree)",
       "Grade: 7.99 / 10 (“Very Good”).",
       ["Thesis: <em>Development and performance study of an algorithm for guaranteed delivery of time-sensitive data flows in micro-cellular wireless networks</em> (graded 10 / 10)."]),
    ]),
    ("Publications & awards", [
      ("2004", "WPMC ’04 · Abano Terme, Italy", "Publication",
       "N. Kalogerinis & M. Paterakis, “Moving Cache Memory Architecture for Efficient Media Streaming Distribution over Wireless Domains”. <em>Seventh International Symposium on Wireless Personal Multimedia Communications</em>, 11–14 September 2004.",
       []),
      ("2004", "State Scholarships Foundation of Greece (IKY)", "Award for excellence",
       "Graduate program of the School of Electronic & Computer Engineering, Technical University of Crete (course average 9.63 / 10).",
       []),
      ("2003", "Ericsson Southeast Europe", "Ericsson Awards of Excellence in Telecommunications",
       "2nd prize for the diploma thesis.",
       []),
    ]),
    ("Teaching & research", [
      ("Spring 2005", "Technical University of Crete", "Lecturer · Production Engineering & Management",
       "Seminar course “Basic Internet Applications and Services”.",
       []),
      ("Spring 2005", "Technical University of Crete", "Instructor · General Department",
       "Lab work, teaching and exams for the undergraduate courses “E-commerce and Computer Networks” and “Scientific Programming” (4th semester).",
       []),
      ("Fall 2005", "Technical University of Crete", "Instructor · General Department",
       "Lab work, teaching and exams for the undergraduate course “Computer Programming” (2nd semester).",
       []),
      ("Mar – Jun 2006", "Technical University of Crete", "Research project “Q-Label”",
       "Digitization of scientific material for an e-learning platform, on Internet Applications & E-commerce and Network Technologies.",
       []),
      ("Mar 2003 – Jan 2005", "EOMMEX · Ministry of Development", "Support & guidance associate, “Go Online” program",
       "Trained staff of small and medium-sized businesses in Crete in internet and e-commerce technologies, helping them get online.",
       []),
      ("Sep 2003 – Jun 2004", "Primary education", "Computer science teacher (hourly)",
       "Computer science in the all-day primary school program; 378 teaching hours.",
       []),
      ("Oct 1999 – Jun 2000", "Technical University of Crete", "Research project “EPET II – Logotypografia”",
       "A Greek dictation system for newsroom workflows: speech recognition, language models, and processing of training samples in Greek.",
       []),
    ]),
    ("Work experience", [
      ("May 2010 – present", "Bank of Greece", "IT Department · Hardware & Operating Systems Support Section",
       "Technical Consultant supporting the Bank's central computing system (mainframe) and its applications.",
       ["IBM z/OS operating system support.",
        "Installation, configuration and maintenance of applications.",
        "Technical support of the MERVA / SWIFT FIN environment.",
        "Management of the backup environment.",
        "Support of the mainframe communications infrastructure (VTAM, SNA, TCP/IP).",
        "Management of storage subsystems (DS8700, TS7740) and the disaster recovery site."]),
      ("Apr 2007 – May 2010", "IBM Hellas", "Infrastructure Specialist · Global Technology Services · IBM System z Product Services – Implementation",
       "Technical specialist supporting IBM zSeries mainframe systems.",
       ["z/OS support (up to V1R9) and its subsystems.",
        "Software installation and configuration through SMP/E; periodic product and function maintenance.",
        "Installation and migration of tape management subsystems (Automated Tape Libraries, Virtual Tape Servers B10/B18, TS7740 Virtualization Engines) and configuration of DFSMSrmm, DFSMShsm and DFSMSdfp OAM.",
        "DFSMS configuration: data management policies, ACS routines, data set allocation and disk organization.",
        "z/OS network services: TCP/IP, FTP, SMTP, TN3270 server, SNA / Enterprise Extender, VTAM; OSA-Express (QDIO and non-QDIO), OSA-ICC and VIPA; equivalent services on z/OS UNIX System Services.",
        "IBM Global Training Services courses: CV86G DB2 V9 for z/OS Implementation Workshop · ES15G z/OS Concepts & Facilities · ES26G SMP/E for z/OS Workshop · SS84G DFSMS Implementation Workshop."]),
      ("Feb 2006 – Feb 2007", "Hellenic Army", "Research & Informatics Corps (military service)",
       "Computer networks and systems administration.",
       ["96th Higher Command, Chios, Brigade Research & Informatics Office: Windows Server 2003 domain with user levels, home folders, access hours and print server permissions; VLANs; backup domain controller (Active Directory replication) and antivirus server (McAfee AutoUpdate Architect) with automatic client updates.",
        "Hellenic Army General Staff IT Support Center, Athens: network administration (Windows 2003), active equipment, VLANs and antivirus server (McAfee ePO); backups of Windows 2003 Server and HP-UX systems. Simulation section: Linux network (Fedora Core 4 & 6), simulation applications, user groups, access levels and print server."]),
      ("Jun – Aug 2005", "Technical University of Crete", "Laboratory instructor · General Department",
       "Lab support for the undergraduate course “Scientific Programming”.",
       ["Lab teaching; preparation of lab exercises and exams.",
        "Writing manuals, notes and teaching material.",
        "Participation in the department's examinations."]),
      ("Nov 2003 – May 2005", "Technical University of Crete", "Full-time project contract · Applied Mathematics & Computers Lab, General Department",
       "Project “Upgrading the Undergraduate Programs of the Technical University of Crete” (EPEAEK II, Measure 2.2).",
       ["System administration on Solaris 9 & 10 with terminal clients.",
        "Network services (POP3, IMAP, Apache with SSL, MySQL) and supporting applications (webmail, anti-spam, content management systems).",
        "Installation and maintenance of MATLAB, Maple, C and Fortran on Solaris.",
        "Development and adaptation of the eClass e-learning platform.",
        "Websites of the General Department and the lab.",
        "Users, groups, access rights and addressing (static IPs and DHCP).",
        "MySQL administration, natively and through phpMyAdmin; backups of user data and databases."]),
    ]),
  ],
},
"el": {
  "lang": "el",
  "title": "Νίκος Καλογερίνης · Βιογραφικό",
  "name": "Νίκος Καλογερίνης",
  "role": "Ηλεκτρονικός Μηχανικός & Μηχανικός Η/Υ",
  "place": "Αθήνα",
  "links": ["www.kalogerinis.net", "github.com/menthol1979"],
  "footer": "Νίκος Καλογερίνης · Βιογραφικό Σημείωμα",
  "page": "Σελίδα",
  "of": "από",
  "extra_title": "Γλώσσες & λοιπά",
  "extra": [
    ("Αγγλικά", "Cambridge Certificate of Proficiency"),
    ("Γαλλικά", "DELF A1, A3, A4"),
    ("Τεχνικό Επιμελητήριο Ελλάδος", "Μέλος ως Ηλεκτρονικός Μηχανικός, 2003 – 2013"),
    ("Στρατιωτικές υποχρεώσεις", "Εκπληρωμένες, 2006 – 2007"),
  ],
  "sections": [
    ("Σπουδές", [
      ("2002 – 2006", "Πολυτεχνείο Κρήτης, Χανιά", "Μεταπτυχιακό Δίπλωμα Ειδίκευσης, Τμήμα Μηχανικών Παραγωγής & Διοίκησης",
       "Τομέας ειδίκευσης: Οργάνωση & Διοίκηση Επιχειρήσεων.",
       ["Διπλωματική εργασία: <em>Ανάπτυξη ενός web-based πολυκριτήριου συστήματος υποστήριξης της λήψης ομαδικών αποφάσεων</em>.",
        "Μέσος όρος μαθημάτων: 8,14 / 10."]),
      ("2002 – 2005", "Πολυτεχνείο Κρήτης, Χανιά", "Μεταπτυχιακό Δίπλωμα Ειδίκευσης, Τμήμα Ηλεκτρονικών Μηχανικών & Μηχανικών Η/Υ",
       "Τομέας ειδίκευσης: Δίκτυα Επικοινωνιών.",
       ["Διπλωματική εργασία: <em>Energy-Aware Scoping Algorithm and Energy Saving Techniques for Wireless Sensor Networks</em>.",
        "Μέσος όρος μαθημάτων: 9,63 / 10."]),
      ("1996 – 2002", "Πολυτεχνείο Κρήτης, Χανιά", "Δίπλωμα Ηλεκτρονικού Μηχανικού & Μηχανικού Η/Υ",
       "Βαθμός διπλώματος: 7,99 / 10 («Λίαν Καλώς»).",
       ["Διπλωματική εργασία: <em>Ανάπτυξη και μελέτη απόδοσης αλγορίθμου εγγυημένης μετάδοσης χρονικά ευαίσθητων ροών δεδομένων σε μικροκυψελωτά ασύρματα δίκτυα</em> (βαθμός 10 / 10)."]),
    ]),
    ("Δημοσιεύσεις & διακρίσεις", [
      ("2004", "WPMC ’04 · Abano Terme, Ιταλία", "Δημοσίευση",
       "N. Kalogerinis & M. Paterakis, “Moving Cache Memory Architecture for Efficient Media Streaming Distribution over Wireless Domains”. <em>Seventh International Symposium on Wireless Personal Multimedia Communications</em>, 11–14 Σεπτεμβρίου 2004.",
       []),
      ("2004", "Ίδρυμα Κρατικών Υποτροφιών (ΙΚΥ)", "Βράβευση άριστης επίδοσης",
       "Μεταπτυχιακό πρόγραμμα του Τμήματος Ηλεκτρονικών Μηχανικών & Μηχανικών Η/Υ του Πολυτεχνείου Κρήτης (μέσος όρος μαθημάτων 9,63 / 10).",
       []),
      ("2003", "Ericsson Southeast Europe", "Ericsson Awards of Excellence in Telecommunications",
       "2ο βραβείο για τη διπλωματική εργασία.",
       []),
    ]),
    ("Εκπαιδευτική & ερευνητική εμπειρία", [
      ("Εαρινό εξάμηνο 2005", "Πολυτεχνείο Κρήτης", "Εισηγητής · Τμήμα Μηχανικών Παραγωγής & Διοίκησης",
       "Σεμιναριακό μάθημα «Βασικές Εφαρμογές και Λειτουργίες Διαδικτύου».",
       []),
      ("Εαρινό εξάμηνο 2005", "Πολυτεχνείο Κρήτης", "Διδάσκων · Γενικό Τμήμα",
       "Εργαστηριακό, διδακτικό και εξεταστικό έργο στα προπτυχιακά μαθήματα «Ηλεκτρονικό Εμπόριο και Δίκτυα Υπολογιστών» και «Επιστημονικός Προγραμματισμός» (4ο εξάμηνο).",
       []),
      ("Χειμερινό εξάμηνο 2005", "Πολυτεχνείο Κρήτης", "Διδάσκων · Γενικό Τμήμα",
       "Εργαστηριακό, διδακτικό και εξεταστικό έργο στο προπτυχιακό μάθημα «Προγραμματισμός Η/Υ» (2ο εξάμηνο).",
       []),
      ("Μάρ. – Ιούν. 2006", "Πολυτεχνείο Κρήτης", "Ερευνητικό πρόγραμμα «Q-Label»",
       "Ψηφιοποίηση επιστημονικού υλικού για πλατφόρμα τηλεκπαίδευσης, στις ενότητες «Εφαρμογές Διαδικτύου – Ηλεκτρονικό Εμπόριο» και «Τεχνολογίες Δικτύων».",
       []),
      ("Μάρ. 2003 – Ιαν. 2005", "ΕΟΜΜΕΧ · Υπουργείο Ανάπτυξης", "Συνεργάτης Υποστήριξης – Καθοδήγησης, πρόγραμμα «Δικτυωθείτε»",
       "Εκπαίδευση στελεχών ΜΜΕ της Κρήτης σε τεχνολογίες διαδικτύου και ηλεκτρονικού εμπορίου και εισαγωγή των επιχειρήσεων στην ηλεκτρονική αγορά.",
       []),
      ("Σεπ. 2003 – Ιούν. 2004", "Πρωτοβάθμια Εκπαίδευση", "Ωρομίσθιος εκπαιδευτικός Πληροφορικής",
       "Πληροφορική στο πρόγραμμα του Ολοήμερου Δημοτικού Σχολείου· 378 ώρες διδασκαλίας.",
       []),
      ("Οκτ. 1999 – Ιούν. 2000", "Πολυτεχνείο Κρήτης", "Ερευνητικό πρόγραμμα «ΕΠΕΤ ΙΙ – Λογοτυπογραφία»",
       "Ελληνικό σύστημα υπαγόρευσης για τη βελτίωση της ροής εργασίας στον δημοσιογραφικό χώρο: αναγνώριση φωνής, γλωσσικά μοντέλα και επεξεργασία δειγμάτων εκπαίδευσης στα ελληνικά.",
       []),
    ]),
    ("Επαγγελματική εμπειρία", [
      ("Μάιος 2010 – σήμερα", "Τράπεζα της Ελλάδος", "Διεύθυνση Πληροφορικής · Τμήμα Υποστήριξης Εξοπλισμού και Λειτουργικών Συστημάτων",
       "Τεχνικός Σύμβουλος στην υποστήριξη του κεντρικού υπολογιστικού συστήματος της Τράπεζας (mainframe) και των εφαρμογών του.",
       ["Υποστήριξη λειτουργικού συστήματος IBM z/OS.",
        "Εγκατάσταση, παραμετροποίηση και συντήρηση εφαρμογών.",
        "Τεχνική υποστήριξη περιβάλλοντος MERVA / SWIFT FIN.",
        "Διαχείριση περιβάλλοντος λήψης αντιγράφων ασφαλείας.",
        "Υποστήριξη υποδομής επικοινωνίας του κεντρικού συστήματος (VTAM, SNA, TCP/IP).",
        "Διαχείριση υποσυστημάτων αποθήκευσης (DS8700, TS7740) και περιβάλλοντος αποκατάστασης από καταστροφή (DR site)."]),
      ("Απρ. 2007 – Μάιος 2010", "IBM Ελλάς", "Infrastructure Specialist · Global Technology Services · IBM System z Product Services – Implementation",
       "Ειδικός Τεχνικός Σύμβουλος στην υποστήριξη υπολογιστικών συστημάτων IBM zSeries (mainframe).",
       ["Υποστήριξη λειτουργικού z/OS (έως V1R9) και υποσυστημάτων.",
        "Εγκατάσταση και παραμετροποίηση λογισμικού μέσω SMP/E και περιοδική συντήρηση προϊόντων και λειτουργιών.",
        "Εγκατάσταση και μετάπτωση υποσυστημάτων διαχείρισης μαγνητικών ταινιών (Automated Tape Libraries, Virtual Tape Servers B10/B18, TS7740 Virtualization Engines) και παραμετροποίηση DFSMSrmm, DFSMShsm και DFSMSdfp OAM.",
        "Παραμετροποίηση DFSMS: πολιτικές διαχείρισης δεδομένων, ρουτίνες ACS, καταμερισμός αρχείων και οργάνωση δίσκων.",
        "Δικτυακές υπηρεσίες σε z/OS: TCP/IP, FTP, SMTP, TN3270 server, SNA / Enterprise Extender, VTAM· OSA-Express (QDIO και non-QDIO), OSA-ICC και VIPA· αντίστοιχες υπηρεσίες σε z/OS UNIX System Services.",
        "Σεμινάρια IBM Global Training Services: CV86G DB2 V9 for z/OS Implementation Workshop · ES15G z/OS Concepts & Facilities · ES26G SMP/E for z/OS Workshop · SS84G DFSMS Implementation Workshop."]),
      ("Φεβ. 2006 – Φεβ. 2007", "Ελληνικός Στρατός", "Σώμα Έρευνας & Πληροφορικής (στρατιωτική θητεία)",
       "Δίκτυα υπολογιστών και διαχείριση συστημάτων.",
       ["96 ΑΔΤΕ, Χίος, Γραφείο Έρευνας & Πληροφορικής Ταξιαρχίας: Domain σε Windows Server 2003 με επίπεδα χρηστών, προσωπικές περιοχές, ωράρια πρόσβασης και δικαιώματα εκτύπωσης μέσω print server· VLANs· backup server (Active Directory replication) και antivirus server (McAfee AutoUpdate Architect) με αυτόματη ενημέρωση των clients.",
        "ΓΕΣ/ΚΕΠΥΕΣ, Αθήνα: διαχείριση δικτύου (Windows 2003), ενεργού εξοπλισμού, VLANs και antivirus server (McAfee ePO)· backup συστημάτων Windows 2003 Server και HP-UX. Τμήμα Προσομοίωσης: δίκτυο Linux (Fedora Core 4 & 6), εφαρμογές προσομοίωσης, ομάδες χρηστών, επίπεδα πρόσβασης και print server."]),
      ("Ιούν. – Αύγ. 2005", "Πολυτεχνείο Κρήτης", "Διδάσκων εργαστηρίου · Γενικό Τμήμα",
       "Εργαστηριακή υποστήριξη του προπτυχιακού μαθήματος «Επιστημονικός Προγραμματισμός».",
       ["Διδακτικό εργαστηριακό έργο· προετοιμασία εργαστηριακών ασκήσεων και εξετάσεων.",
        "Συγγραφή εγχειριδίων, σημειώσεων και εκπαιδευτικού υλικού.",
        "Συμμετοχή στο εξεταστικό έργο του Τμήματος."]),
      ("Νοέ. 2003 – Μάιος 2005", "Πολυτεχνείο Κρήτης", "Σύμβαση έργου πλήρους απασχόλησης · Εργαστήριο Εφαρμοσμένων Μαθηματικών & Η/Υ, Γενικό Τμήμα",
       "Έργο «Αναβάθμιση Προπτυχιακών Προγραμμάτων Σπουδών στο Πολυτεχνείο Κρήτης» (ΕΠΕΑΕΚ ΙΙ, Μέτρο 2.2).",
       ["Διαχείριση συστημάτων Solaris 9 & 10 με terminal clients.",
        "Δικτυακές υπηρεσίες (POP3, IMAP, Apache με SSL, MySQL) και βοηθητικές εφαρμογές (webmail, anti-spam, συστήματα διαχείρισης περιεχομένου).",
        "Εγκατάσταση και συντήρηση MATLAB, Maple, C και Fortran σε Solaris.",
        "Ανάπτυξη και προσαρμογή της πλατφόρμας τηλεκπαίδευσης eClass.",
        "Ιστοσελίδες του Γενικού Τμήματος και του Εργαστηρίου.",
        "Διαχείριση χρηστών, ομάδων, δικαιωμάτων πρόσβασης και διευθυνσιοδότησης (static IPs και DHCP).",
        "Διαχείριση MySQL, natively και μέσω phpMyAdmin· αντίγραφα ασφαλείας δεδομένων χρηστών και βάσεων."]),
    ]),
  ],
},
}
